"""Generate app/src/main/java/com/globe/app/places/CityCatalog.kt from GeoNames dumps.

Usage:
    python tools/generate_city_catalog.py <cities15000.txt> <countryInfo.txt>

Inputs come from https://download.geonames.org/export/dump/ (CC BY 4.0). The catalog is
every capital GeoNames marks (PPLC), plus the most populous places on each inhabited
continent (skipping sections of cities, PPLX, and sub-city districts, PPLA3/PPLA4), plus
the original hand-picked entries, whose IDs must stay stable because saved places and
widget choices refer to them.

It also writes app/src/main/assets/timezone_points_v1.bin (all cities15000 places), which
suggests a time zone for points saved from the globe.
"""
import io
import os
import re
import struct
import sys
import unicodedata

TOP_PER_CONTINENT = 15
CONTINENTS = ["AF", "AS", "EU", "NA", "OC", "SA"]
SKIP_CODES = {"PPLX", "PPLA3", "PPLA4"}
# Original catalog: GeoNames id -> stable app id.
LEGACY = {
    "683506": "city:bucharest",
    "2643743": "city:london",
    "5128581": "city:new-york",
    "1850147": "city:tokyo",
    "2147714": "city:sydney",
    "1273294": "city:delhi",
    "184745": "city:nairobi",
    "3451190": "city:rio",
    "3133895": "city:tromso",
    "3652462": "city:quito",
}
OUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "java",
                   "com", "globe", "app", "places", "CityCatalog.kt")
ZONES_OUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "assets", "timezone_points_v1.bin")


def slug(text):
    ascii_text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", ascii_text.lower()).strip("-")


def kotlin_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def main(cities_path, countries_path):
    countries = {}
    continents = {}
    for line in io.open(countries_path, encoding="utf-8"):
        if not line.startswith("#"):
            fields = line.rstrip("\n").split("\t")
            countries[fields[0]] = fields[4]
            continents[fields[0]] = fields[8]
    rows = []
    for line in io.open(cities_path, encoding="utf-8"):
        f = line.rstrip("\n").split("\t")
        rows.append(dict(gid=f[0], name=f[1], lat=float(f[4]), lon=float(f[5]), fcode=f[7],
                         cc=f[8], pop=int(f[14] or 0), tz=f[17]))
    by_pop = sorted(rows, key=lambda r: -r["pop"])
    chosen = [r for r in rows if r["fcode"] == "PPLC"]
    chosen_ids = {r["gid"] for r in chosen}
    for continent in CONTINENTS:
        biggest = [r for r in by_pop if r["fcode"] not in SKIP_CODES and continents.get(r["cc"]) == continent]
        for r in biggest[:TOP_PER_CONTINENT]:
            if r["gid"] not in chosen_ids:
                chosen.append(r)
                chosen_ids.add(r["gid"])
    legacy_rows = [r for r in rows if r["gid"] in LEGACY]
    missing = set(LEGACY) - {r["gid"] for r in legacy_rows}
    if missing:
        sys.exit("Legacy GeoNames ids missing from input: %s" % sorted(missing))
    chosen += [r for r in legacy_rows if r["gid"] not in chosen_ids]

    used = set()
    entries = []
    for r in sorted(chosen, key=lambda r: slug(r["name"])):
        app_id = LEGACY.get(r["gid"]) or "city:" + slug(r["name"])
        if app_id in used:
            app_id += "-" + r["cc"].lower()
        used.add(app_id)
        label = "%s, %s" % (r["name"], countries[r["cc"]])
        entries.append('        SavedPlace(%s, %s, %s, %s, %s)' % (
            kotlin_string(app_id), kotlin_string(label), repr(r["lat"]), repr(r["lon"]), kotlin_string(r["tz"])))

    body = ",\n".join(entries)
    source = '''package com.globe.app.places

import java.text.Normalizer

/**
 * Offline city list from GeoNames cities15000 (CC BY 4.0); see docs/data-credits.md.
 * Generated by tools/generate_city_catalog.py. Do not edit by hand.
 */
object CityCatalog {
    val cities = listOf(
%s
    )

    /** Accent- and case-insensitive name match; a blank query lists every city. */
    fun search(query: String): List<SavedPlace> {
        val needle = fold(query.trim())
        return cities.filter { needle.isEmpty() || fold(it.name).contains(needle) }.sortedBy { it.name }
    }

    private fun fold(text: String): String =
        Normalizer.normalize(text, Normalizer.Form.NFD).replace(Regex("\\\\p{M}+"), "").lowercase()
}
''' % body
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(source)
    print("Wrote %d cities to %s" % (len(entries), os.path.normpath(OUT)))
    write_zone_points(rows)


def write_zone_points(rows):
    """Every cities15000 place as (lat, lon, zone) for offline time-zone suggestions.

    Big-endian: b"TZP1", u16 zone count, zones as (u8 length, UTF-8), u32 point count,
    then per point i16 lat*100, i16 lon*100, u16 zone index.
    """
    zones = sorted({r["tz"] for r in rows if r["tz"]})
    index = {z: i for i, z in enumerate(zones)}
    points = sorted({(round(r["lat"] * 100), round(r["lon"] * 100), index[r["tz"]]) for r in rows if r["tz"]})
    out = bytearray(b"TZP1") + struct.pack(">H", len(zones))
    for zone in zones:
        encoded = zone.encode("utf-8")
        out += struct.pack(">B", len(encoded)) + encoded
    out += struct.pack(">I", len(points))
    for lat, lon, zone in points:
        out += struct.pack(">hhH", lat, lon, zone)
    with open(ZONES_OUT, "wb") as f:
        f.write(out)
    print("Wrote %d zone points (%d zones, %d bytes) to %s" % (
        len(points), len(zones), len(out), os.path.normpath(ZONES_OUT)))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
