package com.globe.app.places

import android.content.Context
import android.util.Log
import java.io.DataInputStream
import kotlin.math.cos

/**
 * Offline time-zone suggestion from the nearest GeoNames cities15000 place
 * (assets/timezone_points_v1.bin, generated by tools/generate_city_catalog.py).
 * A suggestion only: zone borders do not follow nearest towns everywhere.
 */
object TimeZoneSuggester {
    private const val MAX_DISTANCE_KM = 800.0
    private const val KM_PER_DEGREE = 111.2

    private class Points(val zones: Array<String>, val lat: ShortArray, val lon: ShortArray, val zone: ShortArray)

    @Volatile private var points: Points? = null

    /** Zone of the nearest town within [MAX_DISTANCE_KM], or null (open ocean, poles, missing asset). */
    fun suggest(context: Context, lat: Double, lon: Double): String? {
        val p = load(context) ?: return null
        val cosLat = cos(Math.toRadians(lat))
        var best = -1
        var bestDist = Double.MAX_VALUE
        for (i in p.lat.indices) {
            val dLat = p.lat[i] / 100.0 - lat
            var dLon = Math.abs(p.lon[i] / 100.0 - lon)
            if (dLon > 180.0) dLon = 360.0 - dLon
            val d = dLat * dLat + (dLon * cosLat) * (dLon * cosLat)
            if (d < bestDist) { bestDist = d; best = i }
        }
        if (best < 0 || Math.sqrt(bestDist) * KM_PER_DEGREE > MAX_DISTANCE_KM) return null
        return p.zones[p.zone[best].toInt() and 0xFFFF].takeIf(PlaceStore::validZone)
    }

    private fun load(context: Context): Points? {
        points?.let { return it }
        return synchronized(this) {
            points ?: try {
                DataInputStream(context.assets.open("timezone_points_v1.bin").buffered()).use { input ->
                    val magic = ByteArray(4).also { input.readFully(it) }
                    check(String(magic, Charsets.US_ASCII) == "TZP1") { "Unexpected zone asset" }
                    val zones = Array(input.readUnsignedShort()) {
                        ByteArray(input.readUnsignedByte()).also { input.readFully(it) }.toString(Charsets.UTF_8)
                    }
                    val count = input.readInt()
                    val lat = ShortArray(count)
                    val lon = ShortArray(count)
                    val zone = ShortArray(count)
                    for (i in 0 until count) {
                        lat[i] = input.readShort(); lon[i] = input.readShort(); zone[i] = input.readShort()
                    }
                    Points(zones, lat, lon, zone)
                }.also { points = it }
            } catch (e: Exception) {
                Log.w("TimeZoneSuggester", "Zone points unavailable", e)
                null
            }
        }
    }
}
